const os = require('os')
// console.log(os.freemem())
// console.log(os.homedir())
// console.log(os.arch())
// console.log(os.constants)
// console.log(os.cpus())
// console.log(os.endianness())
// console.log(os.getPriority())
// console.log(os.GetVersionExW())
// console.log(os.networkInterfaces())
console.log(os.platform())
console.log(os.release())
console.log(os.totalmem())
console.log(os.uptime())
console.log(os.type())